//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        public int LessonID { get; set; }
        public int GroupID { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public int TeacherID { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual StudentAttendance StudentAttendance { get; set; }
    }
}
